/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class demo_JNIDemo */

#ifndef _Included_demo_JNIDemo
#define _Included_demo_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_JNIDemo
 * Method:    accessMedthod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_JNIDemo_accessMedthod
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_demo_JNIDemo_accessStaticMethod
(JNIEnv *env, jobject jobj);

#ifdef __cplusplus
}
#endif
#endif
