/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JNIHelloWord */

#ifndef _Included_JNIHelloWord
#define _Included_JNIHelloWord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIHelloWord
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIHelloWord_getStringFromC
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_JNIHelloWord_accessField
(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_JNIHelloWord_plusField
(JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_JNIHelloWord_getStringFrom2C
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
